# Generated by Django 3.1.3 on 2020-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('username', models.CharField(max_length=30, verbose_name='name')),
                ('isPublic', models.BooleanField(default=False, verbose_name='public')),
                ('category', models.CharField(choices=[('default', 'default'), ('python', 'python'), ('c++', 'c++'), ('csharp', 'csharp'), ('javascript', 'javascript')], default='default', max_length=100, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('tags', models.ManyToManyField(related_name='tags', to='post.Tag', verbose_name='tags')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
